### ISSUE TITLE
[QUESTIONS] 

### ISSUE THREAD

**Issue by pandathebeasty** [Ganter1234/Shop-Core#2]
Hello, will be any translation file soon?
Also will be colors supported?
credits command to print in chat to player number of credits?

**Comment by Ganter1234** [comment]
Translations are planned in the next global update

**Comment by pandathebeasty** [comment]
So to not open anther topic, I'm receiving this error, any idea why?

**14:45:16 [EROR] (plugin:Shop Core) {OnClientAuthorized} Failed get info in database | Object reference not set to an instance of an object.**

**Comment by pandathebeasty** [comment]
@Ganter1234 hello, any updates ?

**Comment by szogun1910** [comment]
@Ganter1234 
bump

**Comment by Ganter1234** [comment]
Coming out in an update tomorrow

**Comment by pandathebeasty** [comment]
Which tomorrow?

> Coming out in an update tomorrow

**Comment by Ganter1234** [comment]
> Which tomorrow?
> 
> > Coming out in an update tomorrow

Too many bugs, takes too long
